version: "3.7"
services:
  app:
    image: carlosafrias/php:7.1-cli
    tty: true
    volumes:
      - ../:/usr/src/app
    working_dir: /usr/src/app
    depends_on:
      - db
    user: ${UID:-1000}
    links:
      - db
  db:
    image: mysql:5.7
    volumes:
      - app_db:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "db"

volumes:
  app_db:
